<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE analysis [
<!ELEMENT analysis (section+)>
<!ATTLIST analysis version CDATA #REQUIRED>
<!ATTLIST analysis generated CDATA #REQUIRED>
<!ELEMENT section (item*)>
<!ATTLIST section name CDATA #REQUIRED>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item name CDATA #IMPLIED>
]
>
<analysis version="https://github.com/rfc-st/humble | v.2026-06-13" generated="2026/06/13 - 18:45:23"><section name="[0. Info]"><item name="Date">2026/06/13 - 18:45:23</item><item name="URL">https://en.wikipedia.org</item><item name="File">humble_https_en.wikipedia.org_20260613_184523_en.xml</item></section><section name="[1. Enabled HTTP Security Headers]"><item>Cache-Control</item><item>Content-Security-Policy</item><item>Content-Type</item><item>(*) Nel</item><item>Report-To</item><item>Reporting-Endpoints</item><item>Server-Timing</item><item>Set-Cookie</item><item>Strict-Transport-Security</item><item>X-Content-Type-Options</item></section><section name="[2. Missing HTTP Security Headers]"><item>Clear-Site-Data</item><item>Cross-Origin-Embedder-Policy</item><item>Cross-Origin-Opener-Policy</item><item>Cross-Origin-Resource-Policy</item><item>Integrity-Policy</item><item>(*) Permissions-Policy</item><item>Referrer-Policy</item><item>X-Permitted-Cross-Domain-Policies</item><item>X-Frame-Options</item></section><section name="[3. Fingerprint HTTP Response Headers]"><item>Server</item></section><section name="[4. Deprecated HTTP Response Headers/Protocols and Insecure Values]"><item>Cache-Control (Recommended Values)</item><item>Content-Security-Policy (Deprecated Directives)</item><item>Content-Security-Policy ('base-uri' Directive Missing)</item><item>Content-Security-Policy ('child-src' Directive Missing)</item><item>Content-Security-Policy ('connect-src' Directive Missing)</item><item>Content-Security-Policy ('font-src' Directive Missing)</item><item>Content-Security-Policy ('form-action' Directive Missing)</item><item>Content-Security-Policy ('frame-ancestors' Directive Missing)</item><item>Content-Security-Policy ('img-src' Directive Missing)</item><item>(*) Content-Security-Policy ('require-trusted-types-for' Directive Missing)</item><item>(*) Content-Security-Policy ('trusted-types' Directive Missing)</item><item>Content-Security-Policy ('worker-src' Directive Missing)</item><item>Content-Security-Policy (Too Permissive Sources)</item><item>Content-Security-Policy (Insecure Schemes)</item><item>Content-Security-Policy (Unsafe Eval)</item><item>Content-Security-Policy (Unsafe Inline)</item><item>Report-To (Deprecated Header)</item><item>Server-Timing (Potentially Unsafe Header)</item><item>Vary (Potentially Unsafe Header)</item></section><section name="[5. Empty HTTP Response Headers Values]"><item>Accept-Ch</item><item>X-Analytics</item></section><section name="[6. Browser Compatibility for Enabled HTTP Security Headers]"><item name="Cache-Control">https://caniuse.com/?search=Cache-Control</item><item name="Content-Security-Policy">https://caniuse.com/?search=contentsecuritypolicy2</item><item name="Content-Type">https://caniuse.com/?search=Content-Type</item><item name="NEL">https://caniuse.com/?search=NEL</item><item name="Report-To">https://caniuse.com/?search=Report-To</item><item name="Reporting-Endpoints">https://caniuse.com/?search=Reporting-Endpoints</item><item name="Server-Timing">https://caniuse.com/?search=Server-Timing</item><item name="Set-Cookie">https://caniuse.com/?search=Set-Cookie</item><item name="Strict-Transport-Security">https://caniuse.com/?search=Strict-Transport-Security</item><item name="Vary">https://caniuse.com/?search=Vary</item><item name="X-Content-Type-Options">https://caniuse.com/?search=X-Content-Type-Options</item></section><section name="[7. Analysis Results]"><item>Done in 0.2 seconds! (changes with respect to the last analysis in parentheses)</item><item name="Enabled headers">10 (No changes)</item><item name="Missing headers">9 (No changes)</item><item name="Fingerprint headers">1 (No changes)</item><item name="Deprecated/Insecure headers">19 (No changes)</item><item name="Empty headers">2 (No changes)</item><item name="Findings to review">31 (No changes)</item><item name="Analysis Grade">D (Review 'Deprecated/Insecure headers')</item><item name="'(*)' meaning">Experimental HTTP response directive or header</item><item name="'(*)' ref">https://mdn.io/Experimental_deprecated_obsolete</item><item name="'(Not available)' meaning">The history file, analysis_h.txt, could not be accessed</item></section></analysis>