<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE analysis [
<!ELEMENT analysis (section+)>
<!ELEMENT section (item*)>
<!ATTLIST section name CDATA #REQUIRED>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item name CDATA #IMPLIED>
]
><analysis><section name="[0. Info]"><item name="Date">2024/12/05 - 20:03:52</item><item name="URL">https://facebook.com</item><item name="File">humble_https_facebook_com_20241205_200353_en.xml</item><item name="Note">Exporting to CSV/JSON/XML is currently limited to a brief analysis</item><item name="Note">The URL returns an error (HTTP code 400, 'Bad Request')</item><item name="Ref">https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400</item></section><section name="[1. Enabled HTTP Security Headers]"><item>Cache-Control</item><item>Content-Security-Policy</item><item>Content-Type</item><item>Cross-Origin-Opener-Policy</item><item>Cross-Origin-Opener-Policy-Report-Only</item><item>(*) Origin-Agent-Cluster</item><item>Pragma</item><item>Report-To</item><item>(*) Reporting-Endpoints</item><item>Strict-Transport-Security</item><item>X-Content-Type-Options</item><item>X-Frame-Options</item><item>X-Xss-Protection</item></section><section name="[2. Missing HTTP Security Headers]"><item>Clear-Site-Data</item><item>Cross-Origin-Embedder-Policy</item><item>Cross-Origin-Resource-Policy</item><item>(*) NEL</item><item>(*) Permissions-Policy</item><item>Referrer-Policy</item><item>X-Permitted-Cross-Domain-Policies</item></section><section name="[3. Fingerprint HTTP Response Headers]"><item>X-Fb-Debug</item></section><section name="[4. Deprecated HTTP Response Headers/Protocols and Insecure Values]"><item>Content-Security-Policy (Deprecated Directives)</item><item>Content-Security-Policy (Insecure Schemes)</item><item>Content-Security-Policy (Too Permissive Sources)</item><item>Content-Security-Policy (Unsafe Values)</item><item>Pragma (Deprecated Header)</item><item>Report-To (Deprecated Header)</item><item>Strict-Transport-Security (Recommended Values)</item><item>Strict-Transport-Security (Required Values)</item><item>Vary (Potentially Unsafe Header)</item><item>X-XSS-Protection (Deprecated Header)</item></section><section name="[5. Empty HTTP Response Headers Values]"><item>Nothing to report, all seems OK!</item></section><section name="[6. Browser Compatibility for Enabled HTTP Security Headers]"><item name="Cache-Control">https://caniuse.com/?search=Cache-Control</item><item name="Content-Security-Policy">https://caniuse.com/?search=contentsecuritypolicy2</item><item name="Content-Type">https://caniuse.com/?search=Content-Type</item><item name="Cross-Origin-Opener-Policy">https://caniuse.com/?search=Cross-Origin-Opener-Policy</item><item name="Origin-Agent-Cluster">https://caniuse.com/?search=Origin-Agent-Cluster</item><item name="Reporting-Endpoints">https://caniuse.com/?search=Reporting-Endpoints</item><item name="Strict-Transport-Security">https://caniuse.com/?search=Strict-Transport-Security</item><item name="Vary">https://caniuse.com/?search=Vary</item><item name="X-Content-Type-Options">https://caniuse.com/?search=X-Content-Type-Options</item><item name="X-Frame-Options">https://caniuse.com/?search=X-Frame-Options</item><item name="X-XSS-Protection">https://caniuse.com/?search=X-XSS-Protection</item></section><section name="[7. Analysis Results]"><item>Done in 0.3 seconds! (changes with respect to the last analysis in parentheses)</item><item name="Enabled headers">13 (First Analysis)</item><item name="Missing headers">7 (First Analysis)</item><item name="Fingerprint headers">1 (First Analysis)</item><item name="Deprecated/Insecure headers">10 (First Analysis)</item><item name="Empty headers">0 (First Analysis)</item><item name="Findings to review">18 (First Analysis)</item><item name="Analysis Grade">D (Review 'Deprecated/Insecure headers')</item><item name="'(*)' meaning">Experimental HTTP response header</item><item name="'(*)' ref">https://mdn.io/Experimental_deprecated_obsolete</item></section></analysis>